In [57]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [58]:
# Vector Spaces
print("Vector Spaces:")
# Closure under addition and scalar multiplication
v1 = np.array([1, 2])
v2 = np.array([3, 4])
print(f"Closure under addition: {v1 + v2}")
print(f"Closure under scalar multiplication: {2 * v1}")

Vector Spaces:
Closure under addition: [4 6]
Closure under scalar multiplication: [2 4]


In [59]:
# Span example
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
v3 = np.array([0, 0, 1])
print(f"Span of standard basis: {np.vstack((v1, v2, v3))}")

Span of standard basis: [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [60]:
# Linear independence and dimension
v1 = np.array([1, 0])
v2 = np.array([0, 1])
v3 = np.array([2, 2])
print(f"Linear independence: {np.linalg.matrix_rank(np.vstack((v1, v2, v3))) == 2}")
iris = load_iris()
X = iris.data
print(f"Dimension of iris dataset: {X.shape[1]}")

Linear independence: True
Dimension of iris dataset: 4


In [61]:
# Matrix Operations
print("\nMatrix Operations:")
# Addition, subtraction, and scalar multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(f"A + B:\n{A + B}")
print(f"A - B:\n{A - B}")
print(f"2 * A:\n{2 * A}")


Matrix Operations:
A + B:
[[ 6  8]
 [10 12]]
A - B:
[[-4 -4]
 [-4 -4]]
2 * A:
[[2 4]
 [6 8]]


In [62]:
# Multiplication example
print(f"A * B:\n{A @ B}")

A * B:
[[19 22]
 [43 50]]


In [63]:
# Transpose example
print(f"A^T:\n{A.T}")

A^T:
[[1 3]
 [2 4]]


In [64]:
A = np.array([[1, 4], [2, 3]])
# Eigenvalues and Eigenvectors
print("\nEigenvalues and Eigenvectors:")
# Eigendecomposition example
evals, evecs = np.linalg.eig(A)
print(f"Eigenvalues of A: {evals}")
print(f"Eigenvectors of A: {evecs}")


Eigenvalues and Eigenvectors:
Eigenvalues of A: [-1.  5.]
Eigenvectors of A: [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [65]:
# PCA example
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)
print(f"Explained variance ratio of PCA on iris: {pca.explained_variance_ratio_}")

Explained variance ratio of PCA on iris: [0.92461872 0.05306648]


In [66]:
# Linear Transformations
print("\nLinear Transformations:")
# Scaling example
v = np.array([1, 2, 3])
print(f"2 * v: {2 * v}")


Linear Transformations:
2 * v: [2 4 6]


In [67]:
# Linear Systems  
print("\nLinear Systems:")
# Overdetermined example
A = np.array([[1,2],[3,4],[5,6]])
b = np.array([3,7,11])
x, residuals, _, _ = np.linalg.lstsq(A, b, rcond=None)
print(f"Least squares solution: {x}")


Linear Systems:
Least squares solution: [1. 1.]


In [68]:
# Rotation example
θ = np.pi / 4
R = np.array([[np.cos(θ), -np.sin(θ)], [np.sin(θ), np.cos(θ)]])
print(f"Rotation matrix for π/4: {R}")

Rotation matrix for π/4: [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [69]:
# Additivity and homogeneity
T = lambda v: np.array([2 * v[0], 3 * v[1]])
v1 = np.array([1, 2])
v2 = np.array([3, 4])
print(f"Additivity: T(v1 + v2) = {T(v1 + v2)}, T(v1) + T(v2) = {T(v1) + T(v2)}")
print(f"Homogeneity: T(2 * v1) = {T(2 * v1)}, 2 * T(v1) = {2 * T(v1)}")


Additivity: T(v1 + v2) = [ 8 18], T(v1) + T(v2) = [ 8 18]
Homogeneity: T(2 * v1) = [ 4 12], 2 * T(v1) = [ 4 12]


In [70]:
# Whitening example
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(f"Mean of scaled iris data: {X_scaled.mean(axis=0)}")
print(f"Stddev of scaled iris data: {X_scaled.std(axis=0)}")

Mean of scaled iris data: [-1.69031455e-15 -1.84297022e-15 -1.69864123e-15 -1.40924309e-15]
Stddev of scaled iris data: [1. 1. 1. 1.]


In [71]:
# Linear Systems
print("\nLinear Systems:")
# Representing linear systems
A = np.array([[2, 3], [4, -1]])
b = np.array([5, 3])
print(f"Linear system:\n{A}x = {b}")


Linear Systems:
Linear system:
[[ 2  3]
 [ 4 -1]]x = [5 3]


In [72]:
# Solving using matrix inverse
x = np.linalg.inv(A) @ b
print(f"Solution using matrix inverse: {x}")

Solution using matrix inverse: [1. 1.]


In [79]:
# Solving using Gaussian elimination
A_aug = np.hstack((A, b.reshape(-1, 1)))
print(f"Augmented matrix:\n{A_aug}")
A_ref = A_aug.copy()
A_ref[1] = A_ref[1] - A_ref[0] * A_ref[1, 0] / A_ref[0, 0]
A_ref[1] = A_ref[1] / A_ref[1, 1]
A_ref[0] = A_ref[0] - A_ref[1] * A_ref[0, 1]
A_ref[0] = A_ref[0] / A_ref[0, 0]
print(f"Row echelon form:\n{A_ref}")
x = A_ref[:, 2]
print(f"Solution using Gaussian elimination: {x}")

Augmented matrix:
[[1 2 3 7]
 [4 5 6 8]]
Row echelon form:
[[ 1  0 -1 -5]
 [ 0  1  2  6]]
Solution using Gaussian elimination: [-1  2]


In [81]:
# Overdetermined example
A = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([3, 7, 11])
x, residuals, _, _ = np.linalg.lstsq(A, b, rcond=None)
print(f"Least squares solution: {x}")

Least squares solution: [1. 1.]


In [82]:
# Underdetermined example
A = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([7, 8])
x = np.linalg.pinv(A) @ b
print(f"Minimum norm solution: {x}")

Minimum norm solution: [-3.05555556  0.11111111  3.27777778]


In [86]:
# Application: Recommendation System
print("\nApplication: Recommendation System")
# User-item matrix
R = np.array([[4, 0, 3, 0], [0, 2, 0, 5], [1, 0, 0, 4], [0, 0, 0, 2]])
print(f"User-item matrix:\n{R}")


Application: Recommendation System
User-item matrix:
[[4 0 3 0]
 [0 2 0 5]
 [1 0 0 4]
 [0 0 0 2]]


In [89]:
# Solve system of linear equations
A = np.array([[1, 0, 1, 0], [0, 1, 0, 1], [1, 0, 0, 1]])
b = np.array([4, 2, 1])
x = np.linalg.pinv(A) @ b
print(f"User-item matrix:\n{R}")
print(f"Solution to system of linear equations:\n{x}")

User-item matrix:
[[4 0 3 0]
 [0 2 0 5]
 [1 0 0 4]
 [0 0 0 2]]
Solution to system of linear equations:
[1.00000000e+00 2.00000000e+00 3.00000000e+00 1.11022302e-16]


In [84]:
# Singular Value Decomposition
U, Σ, V = np.linalg.svd(R)
print(f"Left singular vectors:\n{U}")
print(f"Singular values: {Σ}")
print(f"Right singular vectors:\n{V}")

Left singular vectors:
[[-0.10109006  0.98522194  0.12230793  0.06449261]
 [-0.76031483 -0.15376535  0.62997724 -0.03750013]
 [-0.57794593  0.05491501 -0.70804659 -0.4020359 ]
 [-0.27871251 -0.05175215 -0.29468538  0.91257963]]
Singular values: [6.91871065 5.022246   1.35786722 0.25433187]
Right singular vectors:
[[-0.14197821 -0.21978512 -0.04383334 -0.96416561]
 [ 0.79562068 -0.0612337   0.58851475 -0.129956  ]
 [-0.16114601  0.92789225  0.27022066 -0.20007181]
 [-0.56644672 -0.29489135  0.7607298   0.11604904]]


In [85]:
# Low-rank approximation
k = 2
R_approx = U[:, :k] @ np.diag(Σ[:k]) @ V[:k, :]
print(f"Low-rank approximation with k={k}:\n{R_approx}")

Low-rank approximation with k=2:
[[ 4.03605395 -0.14926545  2.94264442  0.03132401]
 [ 0.13244593  1.20344484 -0.22389818  5.17225333]
 [ 0.78714938  0.86195367  0.33758417  3.81951038]
 [ 0.06698965  0.43973388 -0.06843686  1.89300778]]
